[package]
name = "conspiracy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.9.1"
macroquad = "0.3.25"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
